#!/bin/bash
# Build on all platforms and verify everything works properly. This is basically
# like doexport with a few additional commands.
# TODO: Add submit to CRAN
# ftp://cran.r-project.org/incoming and send email to cran@r-project.org
version=
builddate_default=$(date +%F)
upgrade_version=
R=R
export=$(mktemp -d --tmpdir crant.XXXXXXXXXXXX)
sed=sed
readlink=readlink

set_sed()
{
  platform=$(uname -s)
  if [ "$platform" = "Darwin" ]
  then
    echo "NOTE: Using GNU coreutils on Darwin"
    sed=gsed
    readlink=greadlink
  fi
}

fatal()
{
  [ -n "$2" ] && echo "$2" >> /dev/stderr
  exit $1
}

check_fatal()
{
  exitcode=$?
  [ $exitcode -eq 0 ] || fatal $exitcode "$1"
}


do_build()
{
  $R CMD build $binary $vignettes $package
  check_fatal "R CMD build failed"
  if [ -z "$nocheck" ]
  then
    $R CMD check $vignettes $package_src
    check_fatal "R CMD check failed. See $export"
    for t in WARNING NOTE
    do
      if egrep ^$t "$package.Rcheck/00check.log"
      then
        fatal 5 "R CMD check returned $t. See $export"
      fi
    done
  fi
  if [ -n "$docran" ]
  then
    $R CMD check $vignettes --as-cran $package_src
    check_fatal "R CMD check --as-cran failed. See $export"
    for t in WARNING
    do
      if egrep ^$t "$package.Rcheck/00check.log"
      then
        fatal 6 "R CMD check --as-cran returned $t. See $export"
      fi
    done
  fi
}

do_export()
{
  # No need for binary here, since windows packages are built manually
  $R CMD build $vignettes $resavedata $package
  # The built source package is all they want here
  #tar jcf ${package}_${version}.src.tbz2 $package

  # Upload to CRAN
  #TODO: Do this
}

set_windows_path()
{
  # This can be cleaned up more
  if [ -z "$RANT" ]
  then
    RANT="/c/Program Files (x86)/MiKTeX 2.7/miktex/bin:/c/Rtools/bin:/c/Rtools/perl/bin:/c/Rtools/MinGW/bin"
    export PATH=$RANT:$PATH
  fi
  echo "Using PATH=$PATH" >> /dev/stderr
}

# Export to the export directory
do_repo_export()
{
  rm -rf $export/$package > /dev/null 2>&1
  mkdir $export >> /dev/null 2>&1
  if [ -n "$noscm" ]
  then
    cp -R "$package_basename" $export/$package
    rm -rf $export/$package/{.svn,.git,.gitignore,.Rproj.user} >> /dev/null 2>&1
  elif [ -d "$package_basename/.svn" ]
  then
    svn export "$package_basename" $export/$package
  elif [ -d "$package_basename/.git" ]
  then
    mkdir -p $export/$package
    (cd "$package_basename" && git archive HEAD) | tar -x -C $export/$package
  else
    cp -$R "$package_basename" $export/$package
  fi
  cd $export
}

read_package_name()
{
  package_name=$($sed -n -r \
    "/^Package:/{s/^Package:[ \t]+([^ \t]+)[ \t]*$/\1/;p}" DESCRIPTION)
  [ -z "$package_name" ] &&
    fatal 2 "Cannot determine package name. Is your DESCRIPTION file properly formatted?"
  echo -n "$package_name"
}

is_clean_wc()
{
  [ -n "$noautocommit" ] && return
  if [ -d .svn ]
  then
    scm_status=$(svn status)
  elif [ -d .git ]
  then
    scm_status=$(git status --porcelain)
  fi

  if [ -n "$scm_status" ]
  then
    return 1
  else
    return 0
  fi
}

check_clean_wc()
{
  if ! is_clean_wc
  then
    fatal 3 "Working copy is not clean. Exiting."
  fi
}

commit()
{
  [ -n "$noautocommit" ] && return
  message=$1
  shift
  [ -z "$1" ] && return
  if is_clean_wc
  then
    true
  elif [ -d .svn ]
  then
    svn commit -m "$message" $@
  elif [ -d .git ]
  then
    git add $@ && git commit -m "$message"
  fi
}

do_bind_package()
{
  files=$(for file in DESCRIPTION R/$package-package.R man/$package-package.Rd; do
    if [ -f $file ]; then echo $file; fi
  done)
  [ -n "$version" ] && $sed -i -r "
    s/(Version: ([\\]tab |))([0-9.-]+|\{version\})/\1$version/;
    s/(Date: ([\\]tab |))([0-9-]+|\{date\})/\1$builddate/
  " $files 2>/dev/null
  do_roxygenize --no-commit
  commit "Bump version to $version" $files
}

do_roxygenize()
{
  if [ -n "$roxygen" ]; then
    printf "Roxygenizing %s\n" $package >> /dev/stderr
    echo "library(roxygen2); roxygenize('.')" | $R --vanilla
    check_fatal "Error executing roxygenize"
    [ -z "$1" ] && commit "Roxygenize" man DESCRIPTION NAMESPACE
  fi
}

get_current_version()
{
  $sed -n -r "/^Version: /{s/^Version:[ \t]+([^ \t]+)[ \t]*$/\1/;p}" DESCRIPTION
}

get_current_date()
{
  $sed -n -r "/^Date: /{s/^Date:[ \t]+([^ \t]+)[ \t]*$/\1/;p}" DESCRIPTION
}

do_upgrade_version()
{
  pos=$1
  current_version=$(get_current_version)
  v=($(echo -n $current_version |
    $sed -r "s/([0-9]+)([-.])([0-9]+)($|([-.])([0-9]+)($|([-.])([0-9]+)))/\1 \2 \3 \5 \6 \8 \9/"))
  vz=($(echo -n "${v[*]}" | $sed -r "s/[0-9]+/0/g"))
  case $pos in
  1) echo $((${v[0]} + 1))${vz[1]}${vz[2]}${vz[3]}${vz[4]}${vz[5]}${vz[6]};;
  2) echo ${v[0]}${v[1]}$((${v[2]} + 1))${vz[3]}${vz[4]}${vz[5]}${vz[6]};;
  3) if [ -n "${v[4]}" ]; then
       echo ${v[0]}${v[1]}${v[2]}${v[3]}$((${v[4]} + 1))${vz[5]}${vz[6]};
     else
       echo "Warning: Invalid parameter $pos to -u switch" > /dev/stderr;
     fi;;
  4) if [ -n "${v[6]}" ]; then
       echo ${v[0]}${v[1]}${v[2]}${v[3]}${v[4]}${v[5]}$((${v[6]} + 1));
     else
       echo "Warning: Invalid parameter $pos to -u switch" > /dev/stderr;
     fi;;
  *) echo "Warning: Invalid parameter $pos to -u switch" > /dev/stderr;;
  esac
}

set_sed
while getopts "v:Vd:R:DCrSiebwh:xXu:?" opt
do
  case $opt in
  v) version=$OPTARG;;
  d) builddate=$OPTARG;;
  R) R=$OPTARG;;
  D) resavedata=--resave-data;;
  C) nocheck=1;;
  V) vignettes=--no-build-vignettes;;
  r) docran=1; nocheck=1;;
  S) noscm=1; noautocommit=1;;
  i) doinstall=1;;
  e) doexport=1;;
  b) binary="--binary";; # For windows
  x) roxygen=1;;
  X) roxygen=1; roxystop=1;;
  u) upgrade_version=$OPTARG;;
  ?) printf "Usage: %s: [-e] [-v version] [-d date] [path/to/package]\n" $0 >> /dev/stderr
     exit 2;;
  esac
done
shift $(($OPTIND - 1))

package_dir=$1
[ -z "$package_dir" ] && package_dir=.
package_dir=$($readlink -f "$package_dir")

[ "$package_dir" = "/" ] && fatal 4 "Cannot run for root directory."

package_dirname=$(dirname $package_dir)
package_basename=$(basename $package_dir)

cd "$package_dir"

package=$(read_package_name)
check_fatal "Error reading package name"

check_clean_wc

if [ -n "$upgrade_version" ]; then
  version=$(do_upgrade_version $upgrade_version)
  check_fatal "Error upgrading version"
fi

if [ -z "$version" ]; then
  version=$(get_current_version)
  check_fatal "Error reading current version"
  builddate_default=$(get_current_date)
  check_fatal "Error reading current date"
fi

if [ -z "$builddate" ]; then
  builddate=$builddate_default
fi

package_src=${package}_${version}.tar.gz

do_roxygenize
check_fatal "Error roxygenizing"
do_bind_package
check_fatal "Error binding package"
[ -n "$roxystop" ] && exit 0

cd ..

printf "Output directory: %s\n" $export >> /dev/stderr

[ -z "$doexport" ] && printf "Running build chain on %s\n" $package >> /dev/stderr
[ -n "$doexport" ] && printf "Running export on %s\n" $package >> /dev/stderr

# In windows, get the latest source
if [ -n "$binary" ]
then
  set_windows_path
  cd $package
  svn update
  cd -
fi

do_repo_export
check_fatal "Error exporting repository to $export"

if [ -z "$doexport" ]
then
  do_build
  check_fatal "Error building. See $export"
elif [ -n "$doexport" ]
then
  do_export
  check_fatal "Error exporting. See $export"
fi

cd -

if [ -n "$doinstall" ]
then
  echo "Installing package $package" >> /dev/stderr
  $R CMD INSTALL $export/$package_src
  check_fatal "Error installing"
fi

echo "Done with package $package" >> /dev/stderr
