#!/bin/bash
# Set up R libraries
# Example:
#   setuplib.sh -R ~/devel/bin/R RUnit testthat parser
R=R
repo=http://cran.mirrors.hoobly.com

set_toolchain()
{
  platform=$(uname -s)
  if [ "$platform" = "Darwin" ]
  then
    echo "NOTE: Using GNU coreutils on Darwin"
    sed=gsed
    readlink=greadlink
  else
    sed=sed
    readlink=readlink
  fi

  unzip=$(which unzip)
  [ -z "$unzip" ] && unzip='jar xf'
}

function install_package() {
  pkg=$1
  ${R}script --vanilla \
    -e "install.packages('$pkg', repos='$repo', dependencies=$dependencies, INSTALL_opts=$install_opts)"
}

function install_local() {
  package=$(echo $1 | $sed -r 's/.tar$//')
  url=$2
  curl -LO "$url"
  ${R} CMD INSTALL $package.tar.gz
}

function install_source() {
  package=$1
  url=$2
  suffix=$(echo $url | $sed -r 's|.*/.*[.]([a-zA-Z0-9]+)|\1|')
  case $suffix in
    zip)
      curl -LO "$url"
      branch=$(echo $url | $sed -r 's|.*/(.*)[.][a-zA-Z0-9]+|\1|')
      $unzip $branch.zip
      cd ${package}-${branch}
      crant -Ci
      [ -n "$cleanup" ] && rm $branch.zip
      [ -n "$cleanup" ] && rm -rf ${package}-${branch};;
    git)
      git clone $url $package
      cd $package
      crant -Ci
      [ -n "$cleanup" ] && rm -rf $package;;
    *) echo "File of type $suffix is not supported. Sorry.";;
  esac
}

function install_perl() {
  package=$(echo $1 | $sed -r 's/.tar$//')
  url=$2
  curl -LO "$url"
  tar zxf $package.tar.gz
  cd $package
  perl Makefile.PL PREFIX=$perl_lib
  make
  make install
}


function get_package() {
  name=$(echo $1 | $sed -r 's|.*github.com/([^/]+)/([^/]+)/archive/(.*)[.][a-zA-Z0-9]+$|\2|')
  [ "$name" = "$1" ] && name=$(echo $1 | $sed -r 's|.*/(.*)[.][a-zA-Z0-9]+|\1|')
  echo $name
}

function get_suffix() {
  suffix=$(echo $1 | $sed -r 's/.*[.]([a-zA-Z0-9]+)$/\1/')
  [ "$suffix" = "$1" ] && suffix=''
  echo $suffix
}



set_toolchain
dependencies=TRUE
install_opts=NULL
while getopts "cr:tDR:p:" opt
do
  case $opt in
  c) cleanup=yes;;
  r) repo=$OPTARG;;
  t) install_opts='--install-tests';;
  D) dependencies=FALSE;;
  R) R=$OPTARG;;
  p) perl_lib=$OPTARG;;
  esac
done
shift $(($OPTIND - 1))

for pkg in $*
do
  comment=$(echo "$pkg" | grep '^#')
  [ -n "$comment" ] && continue

  echo "Installing $pkg"
  package=$(get_package $pkg)
  suffix=$(get_suffix $pkg)
  [ -n "$perl_lib" ] && suffix=perl

  case $suffix in
    zip) install_source $package $pkg;;
    git) install_source $package $pkg;;
    gz) install_local $package $pkg;;
    perl) install_perl $package $pkg;;
    *) install_package $pkg;;
  esac
done

